# Generated by Django 4.2.13 on 2024-05-23 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.TimeField(auto_now_add=True)),
                ('completion_time', models.TimeField(auto_now_add=True)),
                ('language', models.CharField(choices=[('ES', 'Spanish'), ('ZH', 'Traditional Chinese/Simplified Chinese'), ('VI', 'Vietnamese'), ('EN', 'English'), ('UK', 'Ukrainian'), ('RU', 'Russian'), ('AR', 'Arabic'), ('HT', 'Haitian Creole'), ('FA', 'Persian'), ('LO', 'Lao')], max_length=2)),
                ('family_size', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('Other', 'Other')], max_length=5)),
                ('snap_benefits', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3)),
                ('travel_by_car', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3)),
                ('zip_code', models.CharField(choices=[('97206', '97206'), ('97213', '97213'), ('97216', '97216'), ('97218', '97218'), ('97220', '97220'), ('97230', '97230'), ('97233', '97233'), ('97236', '97236'), ('97266', '97266'), ('Other', 'Other')], max_length=5)),
            ],
        ),
    ]
