# Generated by Django 5.0.6 on 2024-08-15 00:39

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('modified_timestamp', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField()),
                ('abbreviation', models.CharField()),
                ('prompt', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('modified_timestamp', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('question', models.TextField()),
                ('answer_choices', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), size=None)),
                ('has_other', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ClientLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('language_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_handler_app.language')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('answer', models.CharField(max_length=255)),
                ('deleted', models.BooleanField(default=False)),
                ('client_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_handler_app.clientlanguage')),
                ('question_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_handler_app.question')),
            ],
        ),
        migrations.CreateModel(
            name='TranslatedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('modified_timestamp', models.DateTimeField(auto_now_add=True)),
                ('question', models.TextField()),
                ('answer_choices', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), size=None)),
                ('other', models.CharField()),
                ('language_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_handler_app.language')),
                ('question_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_handler_app.question')),
            ],
        ),
    ]
