# Generated by Django 5.0.6 on 2024-06-06 19:35

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.TimeField(auto_now_add=True)),
                ('completion_time', models.TimeField(auto_now_add=True)),
                ('language', models.CharField(choices=[('ES', 'Spanish'), ('ZH', 'Traditional Chinese/Simplified Chinese'), ('VI', 'Vietnamese'), ('EN', 'English'), ('UK', 'Ukrainian'), ('RU', 'Russian'), ('AR', 'Arabic'), ('HT', 'Haitian Creole'), ('FA', 'Persian'), ('LO', 'Lao')], max_length=2)),
                ('family_size', models.PositiveIntegerField()),
                ('snap_benefits', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3)),
                ('travel_by_car', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3)),
                ('zip_code', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('modified_timestamp', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('question', models.TextField()),
                ('answer_choices', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), size=None)),
                ('has_other', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('answer', models.CharField(max_length=255)),
                ('client_id', models.IntegerField()),
                ('deleted', models.BooleanField(default=False)),
                ('question_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_handler_app.questions')),
            ],
        ),
    ]
