# Generated by Django 5.0.6 on 2024-06-22 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerType',
            fields=[
                ('answer_type_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('type_name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('language_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('language_abreviation', models.CharField()),
                ('language_name', models.CharField()),
                ('language_prompt', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('language_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_handler_app.language')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('question_type_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('question_name', models.CharField()),
                ('display_on_questionnaire', models.BooleanField(default=True)),
                ('display_order', models.IntegerField()),
                ('answer_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_handler_app.answertype')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionTranslation',
            fields=[
                ('question_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('question_text', models.CharField()),
                ('language_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_handler_app.language')),
                ('question_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_handler_app.questiontype')),
            ],
        ),
        migrations.CreateModel(
            name='ClientAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_answer', models.CharField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_handler_app.client')),
                ('question_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_handler_app.questiontype')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerTranslation',
            fields=[
                ('answer_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('associated_boolean', models.BooleanField(null=True)),
                ('associated_integer', models.IntegerField(null=True)),
                ('associated_text', models.CharField(null=True)),
                ('answer_text', models.CharField()),
                ('language_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_handler_app.language')),
                ('question_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_handler_app.questiontype')),
            ],
        ),
    ]
