# Generated by Django 4.2.13 on 2024-05-23 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdata',
            name='family_size',
            field=models.PositiveIntegerField(),
        ),
    ]
