# Generated by Django 5.0.6 on 2024-06-28 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler_app', '0002_answertype_language_client_questiontype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerTypes',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField()),
                ('abreviation', models.CharField()),
                ('prompt', models.CharField()),
            ],
        ),
        migrations.RemoveField(
            model_name='questiontype',
            name='answer_type_id',
        ),
        migrations.RemoveField(
            model_name='client',
            name='language_id',
        ),
        migrations.RemoveField(
            model_name='clientanswer',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='clientanswer',
            name='question_type_id',
        ),
        migrations.RemoveField(
            model_name='questiontranslation',
            name='language_id',
        ),
        migrations.RemoveField(
            model_name='questiontranslation',
            name='question_type_id',
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('language_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_handler_app.languages')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionTypes',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField()),
                ('display_on_questionnaire', models.BooleanField(default=True)),
                ('display_order', models.IntegerField()),
                ('answer_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_handler_app.answertypes')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionTranslations',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('translation', models.CharField()),
                ('language_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_handler_app.languages')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_handler_app.questiontypes')),
            ],
        ),
        migrations.CreateModel(
            name='ClientAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_handler_app.clients')),
                ('question_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_handler_app.questiontypes')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerTranslations',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('associated_boolean', models.BooleanField(null=True)),
                ('associated_integer', models.IntegerField(null=True)),
                ('associated_text', models.CharField(null=True)),
                ('translation', models.CharField()),
                ('language_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_handler_app.languages')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_handler_app.questiontypes')),
            ],
        ),
        migrations.DeleteModel(
            name='AnswerTranslation',
        ),
        migrations.DeleteModel(
            name='AnswerType',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='ClientAnswer',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='QuestionTranslation',
        ),
        migrations.DeleteModel(
            name='QuestionType',
        ),
    ]
