# Generated by Django 4.2.13 on 2024-05-23 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler_app', '0002_alter_clientdata_family_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdata',
            name='zip_code',
            field=models.CharField(max_length=5),
        ),
    ]
