# Generated by Django 5.0.6 on 2024-07-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler_app', '0003_answer_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddTester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=2)),
                ('family_size', models.PositiveIntegerField()),
                ('snap_benefits', models.CharField(max_length=3)),
                ('travel_by_car', models.CharField(max_length=3)),
                ('zip_code', models.CharField(max_length=5)),
            ],
        ),
        migrations.DeleteModel(
            name='ClientData',
        ),
    ]
