# Generated by Django 5.0.6 on 2024-07-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler_app', '0004_addtester_delete_clientdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtester',
            name='snap_benefits',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='addtester',
            name='travel_by_car',
            field=models.CharField(),
        ),
    ]
