# Generated by Django 4.2.13 on 2024-06-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler_app', '0004_questions_rename_date_clientdata_created_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdata',
            name='client_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
