# Generated by Django 5.0.6 on 2024-07-03 16:42

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler_app', '0005_alter_addtester_snap_benefits_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('modified_timestamp', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField()),
                ('abbreviation', models.CharField()),
                ('prompt', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='TranslatedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('modified_timestamp', models.DateTimeField(auto_now_add=True)),
                ('question', models.TextField()),
                ('answer_choices', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), size=None)),
                ('other', models.CharField()),
                ('language_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_handler_app.language')),
            ],
        ),
        migrations.DeleteModel(
            name='AddTester',
        ),
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
        migrations.AddField(
            model_name='translatedquestion',
            name='question_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_handler_app.question'),
        ),
    ]
