# Generated by Django 4.2.13 on 2024-06-04 17:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler_app', '0005_clientdata_client_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdata',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='clientdata',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='clientdata',
            name='created_timestamp',
        ),
        migrations.RemoveField(
            model_name='clientdata',
            name='question_fk',
        ),
        migrations.AddField(
            model_name='clientdata',
            name='completion_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientdata',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientdata',
            name='family_size',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientdata',
            name='language',
            field=models.CharField(choices=[('ES', 'Spanish'), ('ZH', 'Traditional Chinese/Simplified Chinese'), ('VI', 'Vietnamese'), ('EN', 'English'), ('UK', 'Ukrainian'), ('RU', 'Russian'), ('AR', 'Arabic'), ('HT', 'Haitian Creole'), ('FA', 'Persian'), ('LO', 'Lao')], default=None, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientdata',
            name='snap_benefits',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default=None, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientdata',
            name='start_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientdata',
            name='travel_by_car',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default=None, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientdata',
            name='zip_code',
            field=models.CharField(default=None, max_length=5),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('answer', models.CharField(max_length=255)),
                ('client_id', models.IntegerField()),
                ('question_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_handler_app.questions')),
            ],
        ),
    ]
