from django.db import models
from django.contrib.postgres.fields import ArrayField

class Questions(models.Model):
    created_timestamp = models.DateTimeField(auto_now_add=True)
    modified_timestamp = models.DateTimeField(auto_now_add=True)
    deleted = models.BooleanField(default=False)
    question = models.TextField()
    answer_choices = ArrayField(models.CharField(blank=False))
    has_other = models.BooleanField()

    def __str__(self):
        return self.question

class ClientData(models.Model):
    # id field is automatically generated by django, we
    # can create seperate id's for daily visitors, monthly
    # visitors, etc.
    created_timestamp = models.DateTimeField(auto_now_add=True)
    question_fk = models.ForeignKey("Questions", on_delete=models.SET_NULL, null=True)
    answer = models.CharField(max_length=255)

    def __str__(self):
        return self.answer
    