from django.db import models
from django.contrib.postgres.fields import ArrayField 

class Languages(models.Model):
    id = models.BigIntegerField(primary_key=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now_add=True)
    name = models.CharField()
    abreviation = models.CharField()
    prompt = models.CharField()

    def __str__(self):
        return self.name
    
class Clients(models.Model):
    id = models.BigIntegerField(primary_key=True)
    language_id = models.ForeignKey(Languages, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.id  
    
class AnswerTypes(models.Model):
    id = models.BigIntegerField(primary_key=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now_add=True)
    name = models.CharField()

    def __str__(self):
        return self.name

class QuestionTypes(models.Model):
    id = models.BigIntegerField(primary_key=True)
    answer_type_id = models.ForeignKey(AnswerTypes, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now_add=True)
    name = models.CharField()
    display_on_questionnaire = models.BooleanField(default=True)
    display_order = models.IntegerField()

    def __str__(self):
        return self.name

class ClientAnswers(models.Model):
    client_id = models.ForeignKey(Clients, on_delete=models.CASCADE)
    question_type_id = models.ForeignKey(QuestionTypes, on_delete=models.CASCADE)
    data = models.CharField()

    def __str__(self):
        return self.data
    
class QuestionTranslations(models.Model):
    id = models.BigIntegerField(primary_key=True)
    question_id = models.ForeignKey(QuestionTypes, on_delete=models.CASCADE)
    language_id = models.ForeignKey(Languages, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now_add=True)
    translation = models.CharField()

    def __str__(self):
        return self.translation 

class AnswerTranslations(models.Model):
    id = models.BigIntegerField(primary_key=True)
    question_id = models.ForeignKey(QuestionTypes, on_delete=models.CASCADE)
    language_id = models.ForeignKey(Languages, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now_add=True)
    associated_boolean = models.BooleanField(null=True)
    associated_integer = models.IntegerField(null=True)
    associated_text = models.CharField(null=True)
    translation = models.CharField()

    def __str__(self):
        return self.translation  


#***************************************************************************************************
# older models kept in until previous views are updated
#***************************************************************************************************

class Questions(models.Model):
    created_timestamp = models.DateTimeField(auto_now_add=True)
    modified_timestamp = models.DateTimeField(auto_now_add=True)
    deleted = models.BooleanField(default=False)
    question = models.TextField()
    answer_choices = ArrayField(models.CharField(blank=False))
    has_other = models.BooleanField()

    def __str__(self):
        return self.question

class Answer(models.Model):
    created_timestamp = models.DateTimeField(auto_now_add=True)
    question_fk = models.ForeignKey("Questions", on_delete=models.SET_NULL, null=True)
    answer = models.CharField(max_length=255)
    client_id = models.IntegerField()
    deleted = models.BooleanField(default=False)

    def __str__(self):
        return self.answer

class ClientData(models.Model):
    # id field is automatically generated by django, we
    # can create seperate id's for daily visitors, monthly
    # visitors, etc.
    date = models.DateTimeField(auto_now_add=True)
    start_time = models.TimeField(auto_now_add=True)
    completion_time = models.TimeField(auto_now_add=True)

    LANGUAGE_CHOICES = [
        ('ES', 'Spanish'),
        ('ZH', 'Traditional Chinese/Simplified Chinese'),
        ('VI', 'Vietnamese'),
        ('EN', 'English'),
        ('UK', 'Ukrainian'),
        ('RU', 'Russian'),
        ('AR', 'Arabic'),
        ('HT', 'Haitian Creole'),
        ('FA', 'Persian'),
        ('LO', 'Lao'),
    ]
    language = models.CharField(max_length=2, choices=LANGUAGE_CHOICES)

    family_size = models.PositiveIntegerField()

    SNAP_BENEFITS_CHOICES = [
        ('YES', 'Yes'),
        ('NO', 'No'),
    ]
    snap_benefits = models.CharField(max_length=3, choices=SNAP_BENEFITS_CHOICES)

    TRAVEL_BY_CAR_CHOICES = [
        ('YES', 'Yes'),
        ('NO', 'No'),
    ]
    travel_by_car = models.CharField(max_length=3, choices=TRAVEL_BY_CAR_CHOICES)

    zip_code = models.CharField(max_length=5)
     

    
    